WITH ads_performance AS(
SELECT
    CAST(ad_id AS STRING),
    CAST(NULL AS INT64) AS add_to_cart,
    CAST(adset_id AS STRING),
    campaign_id,
    channel,
    clicks,
    CAST(NULL AS INT64) AS comments,
    NULL AS creative_id,
    CAST(__insert_date AS DATE) AS date,
    CAST(NULL AS INT64) AS engagements,
    imps AS impressions,
    CAST(NULL AS INT64) AS installs,
    CAST(NULL AS INT64) AS likes,
    CAST(NULL AS INT64) AS link_clicks,
    CAST(NULL AS STRING) AS placement_id,
    CAST(NULL AS INT64) AS post_click_conversions,
    CAST(NULL AS INT64) AS post_view_conversions,
    CAST(NULL AS INT64) AS posts,
    CAST(NULL AS INT64) AS purchase,
    CAST(NULL AS INT64) AS registrations,
    revenue,
    CAST(NULL AS INT64) AS shares,
    spend,
    conv AS total_conversions,
    CAST(NULL AS INT64) AS video_views
FROM
    {{ref("src_ads_bing_all_data")}}
UNION ALL
SELECT
    CAST(ad_id AS STRING),
    add_to_cart,
    CAST(NULL AS STRING) AS adset_id,
    campaign_id,
    channel,
    clicks,
    CAST(NULL AS INT64) AS comments,
    NULL AS creative_id,
    CAST(__insert_date AS DATE) AS date,
    CAST(NULL AS INT64) AS engagements,
    impressions,
    CAST(NULL AS INT64) AS installs,
    CAST(NULL AS INT64) AS likes,
    CAST(NULL AS INT64) AS link_clicks,
    CAST(NULL AS STRING) AS placement_id,
    CAST(NULL AS INT64) AS post_click_conversions,
    CAST(NULL AS INT64) AS post_view_conversions,
    CAST(NULL AS INT64) AS posts,
    purchase,
    registrations,
    CAST(NULL AS INT64) AS revenue,
    CAST(NULL AS INT64) AS shares,
    spend,
    conversions AS total_conversions,
    video_views
FROM
    {{ref('src_ads_tiktok_ads_all_data')}}
UNION ALL
SELECT
    CAST(NULL AS STRING) AS ad_id,
    CAST(NULL AS INT64) AS add_to_cart,
    CAST(NULL AS STRING) AS adset_id,
    campaign_id,
    channel,
    clicks,
    comments,
    NULL AS creative_id,
    CAST(__insert_date AS DATE) AS date,
    engagements,
    impressions,
    CAST(NULL AS INT64) AS installs,
    likes,
    url_clicks AS link_clicks,
    CAST(NULL AS STRING) AS placement_id,
    CAST(NULL AS INT64) AS post_click_conversions,
    CAST(NULL AS INT64) AS post_view_conversions,
    CAST(NULL AS INT64) AS posts,
    CAST(NULL AS INT64) AS purchase,
    CAST(NULL AS INT64) AS registrations,
    CAST(NULL AS INT64) AS revenue,
    retweets AS shares,
    spend,
    CAST(NULL AS INT64) AS total_conversions,
    video_total_views AS video_views
FROM
    {{ref("src_promoted_tweets_twitter_all_data")}}
UNION ALL
SELECT
    CAST(ad_id AS STRING),
    add_to_cart,
    CAST(adset_id AS STRING),
    campaign_id,
    channel,
    clicks,
    comments,
    creative_id,
    CAST(__insert_date AS DATE) AS date,
    (likes + shares + comments + views + clicks + mobile_app_install + complete_registration) AS engagements,
    impressions,
    mobile_app_install AS installs,
    likes,
    inline_link_clicks AS link_clicks,
    CAST(NULL AS STRING) AS placement_id,
    CAST(NULL AS INT64) AS post_click_conversions,
    CAST(NULL AS INT64) AS post_view_conversions,
    CAST(NULL AS INT64) AS posts,
    purchase,
    complete_registration AS registrations,
    purchase_value AS revenue,
    shares,
    spend,
    purchase AS total_conversions,
    CAST(NULL AS INT64) AS video_views
FROM
    {{ref("src_ads_creative_facebook_all_data")}})

select * from ads_performance